### ISSUE TITLE
Style Posts / Post List

### ISSUE THREAD

**Issue by scottyg** [deer/fresh_blog#12]
Is there a way to style the post page and the post list on the index page using tailwind? I've looked though the code and it doesn't look like this functionality is there, but perhaps I am wrong. Is this something that may be added in the future? If so, I wouldn't mind tying to implement that.

**Comment by deer** [comment]
Hi Scott, thanks for logging this. I didn't think anyone was actually interested in this (yet), since it's still so rough. But I guess you've inspired me to be more open about my roadmap. Literally the next item on my list is "add ability to configure styles" which I think is the same as this request. I'll go and add items for the other things I want to tackle as well.

It looks like you're in Las Vegas, so perhaps I'll have a solution to this by the time you wake up. If so I hope you can give some feedback on the solution.

**Comment by deer** [comment]
I started looking at this a few hours ago, and I've determined that I'm not very good at CSS. I will try again tomorrow.

**Comment by scottyg** [comment]
I wonder if instead of allowing the customizing of css or classes you could allow the post data to be accessed to new user built components? Maybe allow access to some of the functions in utils/posts.ts through an export?

**Comment by deer** [comment]
@scottyg, I've finally completed this. There are some details on the closed PR, #33.
