### ISSUE TITLE
Upgrade to Fresh 1.4

### ISSUE THREAD

**Issue by scottyg** [deer/fresh_blog#20]
We should upgrade the plugin to Fresh 1.4 and do the notion refactoring before adding new functionality to avoid the build errors.

**Comment by deer** [comment]
Thanks again for your continued interest. I must admit I'm a bit confused about this one though. The current forked version (https://github.com/deer/fresh/commits/feat_plugin_islands, which is what I'm requesting to merge into main in the PR) is currently sitting right at 1.4.2. Is there any action to take here until the islands PR moves forward?

To clarify, switching away from the forked version will break islands functionality. This might not be bad, since not all tests leverage the responsive navbar island, but I also don't see the benefit either. To me the sensible thing remains:
1. get the PR to fresh merged (Marvin is on vacation and will look at it next week when he's back)
2.  remove all the references to the forked version from the codebase (the actual code, plus all the test fixtures)
3. make sure all the functionality is documented (it's not, and this is on me to fix!)
4. release 0.1.0!

**Comment by scottyg** [comment]
This makes sense! 0.1.0 let's go!

**Comment by deer** [comment]
This was a long time coming, but islands via plugins finally landed. This is closed by #26. I'm working on sorting out the styling situation again, because that's really bad. But I did release a https://deno.land/x/fresh_blog@0.0.4 in the mean time. https://github.com/deer/fresh_blog/releases/tag/0.0.4 has all the details (which is fairly boring).
